// flow-typed signature: c5d0fdef4ee18b3112f7dec055441e0e
// flow-typed version: <<STUB>>/uglifyjs2_v^0.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyjs2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyjs2' {
  declare module.exports: any;
}
